# -*- coding: utf-8 -*-
"""Texte des evenements aleatoires des 4 regimes du scenario historique,
d'apres la traduction v7 (assets/pdf/evenements_aleatoires_fr.pdf)."""

EVENT_TEXT = {
    'Legislative': {
        'economy': {
            2: "Expédition de la garde nationale de Marseille contre les aristocrates d'Arles. Révolte neutre à Marseille, Clergé -2.",
            3: "Massacre des détenus de la Glacière à Avignon. Révolte neutre à Marseille.",
            4: "Les paysans du Bordelais attaquent les châteaux. Bordeaux devient neutre.",
            5: "Les paysans du Lot attaquent les châteaux. Cahors devient neutre.",
            6: "Les paysans du Limousin attaquent les châteaux. Limoges devient neutre.",
            7: "Troubles agraires à Nîmes. Le courant qui contrôle Nîmes rend 200 assignats.",
            8: "Troubles agraires à Rouen. Le courant qui contrôle Rouen rend 300 assignats.",
            9: "Émeutes agraires à Amiens. Amiens devient neutre.",
            10: "Émeutes agraires à Lille. Lille devient neutre.",
            11: "Émeutes agraires à Orléans. Révolte neutre à Orléans.",
            12: "Émeutes agraires à Dijon. Révolte neutre à Dijon.",
        },
        'politics': {
            2: "Discours de Brissot pour la guerre. Renommée Gironde +1, Coalisés +2.",
            3: "Articles de Marat contre le bellicisme girondin. Renommée Gironde -1.",
            4: "Discours de Robespierre contre la guerre. Renommée Gironde -1, Coalisés -1.",
            5: "La Fayette réclame la guerre. Renommée Feuillant +1, Coalisés +1.",
            6: "Lameth, Duport et Dubois-Crancé s'opposent à la guerre. Renommée Feuillant -1, Coalisés -1.",
            7: "Le salon de Mme de Staël : le Feuillant a +2 pour retourner députés et personnalités ce tour.",
            8: "Le salon de Manon Roland : la Gironde a +2 pour retourner députés et personnalités ce tour.",
            9: "Discours de Jacques Roux sur les moyens de sauver la France. Renommée Sans-Culotte +1.",
            10: "Robespierre l'emporte sur Brissot au club des Jacobins. Renommée Montagne +1, Gironde -1.",
            11: "Rochambeau, Luckner et La Fayette suspendent les hostilités : l'armée de Lille ne combat pas ce tour (elle se défend si on l'attaque).",
            12: "Offensive girondine et montagnarde contre le « comité autrichien » des Tuileries. Renommée Gironde et Montagne +1.",
        },
        'counter': {
            2: "Louis XVI écrit à l'Empereur pour qu'il déclare la guerre. Coalisés +2.",
            3: "Marie-Antoinette écrit à Fersen pour pousser Vienne et Berlin à la guerre. Coalisés +2.",
            4: "Louis XVI s'oppose aux rassemblements d'émigrés. Coalisés et Clergé +1, Commune -1.",
            5: "Alliance austro-prussienne pour envahir la France. Coalisés +2.",
            6: "Querelle austro-prussienne sur la Pologne. Coalisés -2.",
            7: "Émeute royaliste à Brest : Brest devient neutre, sauf si le Royaliste la contrôle.",
            8: "Émeute royaliste à Nîmes : Nîmes devient neutre, sauf si le Royaliste la contrôle.",
            9: "Complot d'insurrection dans l'Ouest. Clergé +2.",
            10: "Révolte royaliste à Arles : le Royaliste prend Marseille et sa révolte. Clergé +1.",
            11: "Une armée révolutionnaire au choix du Royaliste déserte et quitte la carte.",
            12: "Manifeste de Brunswick menaçant les Parisiens. Commune et Clergé +3.",
        },
        'commune': {
            2: "Journée des Tuileries : la Gironde prend Paris et la Commune.",
            3: "La Commune demande la déchéance du Roi : l'Assemblée vote. Oui : Commune -2, Renommée Feuillant et Marais -1. Non : Commune +2, Renommée Feuillant +1.",
            4: "Les Parisiennes demandent des piques ; le Gouvernement décide. Oui : Commune -1, Renommée Gouvernement +1. Non : Commune +1, Renommée Gouvernement -1.",
            5: "La Fayette menace de faire un coup d'État. Commune +2.",
            6: "Fête de la Fédération. Commune +1.",
            7: "Fête des Suisses de Châteauvieux libérés. Commune -2.",
            8: "Fête de la Loi. Commune +1.",
            9: "Contre l'agiotage, les Jacobins et les Cordeliers renoncent au sucre et au café. Économie +2.",
            10: "La Commune demande des fonds pour nourrir le peuple ; le Gouvernement décide. Oui : Commune -2, 300 assignats. Non : Commune +2, Renommée Gouvernement -2.",
            11: "Les Parisiens refusent l'impôt : le Gouvernement rend 500 assignats.",
            12: "Émeute du sucre : Paris devient neutre et la Commune se soulève.",
        },
    },
    'Convention': {
        'economy': {
            2: "Révolte des Enragés de Chalier à Lyon : le Sans-Culotte prend Lyon, en révolte.",
            3: "Révolte des Enragés de Taroubeau à Orléans : le Sans-Culotte prend Orléans, en révolte.",
            4: "Révolte des Enragés de Taroubeau à Tours : le Sans-Culotte prend Tours, en révolte.",
            5: "Taxations agraires à Orléans : le courant qui la contrôle rend 200 assignats (sauf le Sans-Culotte).",
            6: "Taxations agraires à Tours : le courant qui la contrôle rend 100 assignats (sauf le Sans-Culotte).",
            7: "Taxations agraires à Montpellier : le courant qui la contrôle rend 200 assignats (sauf le Sans-Culotte).",
            8: "Taxations agraires à Amiens : le courant qui la contrôle rend 300 assignats (sauf le Sans-Culotte).",
            9: "Révolte agraire à Dijon : la région devient neutre et se révolte.",
            10: "Révolte agraire à Montpellier : la région devient neutre et se révolte.",
            11: "Révolte agraire à Metz : la région devient neutre et se révolte.",
            12: "Révolte agraire à Rouen : la région devient neutre et se révolte.",
        },
        'politics': {
            2: "Discours de Saint-Just pour l'exécution du Roi : +4 pour la condamnation si le procès a lieu ce tour.",
            3: "Les Girondins réclament l'appel au peuple : -2 pour la condamnation au procès ce tour.",
            4: "(En guerre) La Fayette et Lameth passent à l'ennemi : -1 aux combats à Metz ce tour ; La Fayette et Lameth hors jeu jusqu'à la paix.",
            5: "Offensive de Brissot et Vergniaud contre la Commune. Renommée Gironde -1, Commune -2.",
            6: "Des Girondins accusent Marat de troubler l'ordre. Commune +2, le Gouvernement a +2 pour arrêter Marat.",
            7: "Discours de Roland contre la Montagne. Renommée Montagne -1.",
            8: "Roux dénonce la famine et la modération des Montagnards. Renommée Montagne -1.",
            9: "Robespierre accuse les Girondins d'être ennemis de la patrie. Renommée Gironde -1.",
            10: "Marat accuse les Girondins de feuillantisme. Renommée Gironde -1.",
            11: "Les Girondins créent une commission de surveillance de la Commune. Commune -3.",
            12: "Journée d'insurrection contre la Gironde prônée par Marat : le Sans-Culotte prend la Commune. Commune +3.",
        },
        'counter': {
            2: "Révolte à Cholet : le Royaliste prend Cholet et sa révolte.",
            3: "Défense énergique des avocats du Roi : -2 pour la condamnation au procès ce tour.",
            4: "Les armées révolutionnaires de Lille ou d'Amiens (au choix du Gouvernement) reculent sans raison apparente.",
            5: "Nice et la Savoie demandent leur rattachement à la France : l'armée sarde se retire.",
            6: "(En guerre) Trahison de Montesquiou, chef de l'armée des Alpes : les armées révolutionnaires de Marseille (ou la plus proche) sont retirées.",
            7: "Émeute royaliste en Dauphiné : Marseille devient neutre, sauf si le Royaliste la contrôle.",
            8: "Émeute royaliste à Lyon : Lyon devient neutre, sauf si le Royaliste la contrôle.",
            9: "Émeute royaliste à Rouen : Rouen devient neutre, sauf si le Royaliste la contrôle.",
            10: "Révolte de Charrier en Lozère : le Royaliste prend Nîmes et sa révolte.",
            11: "(Si Louis XVI est mort) Le comte de Provence se proclame régent. Clergé +2.",
            12: "(En guerre) Dumouriez passe à l'ennemi avec son armée : les armées de Lille ou d'Amiens sont retirées ; l'armée de Cobourg revient si elle avait été éliminée.",
        },
        'commune': {
            2: "Une délégation de la Commune refuse l'appel au peuple : +2 pour la condamnation au procès ce tour.",
            3: "Massacres dans les prisons : les personnalités royalistes et feuillantes détenues au Temple sont tuées (sauf Louis XVI).",
            4: "Massacres dans les prisons : les personnalités royalistes et feuillantes détenues au Temple sont tuées (sauf Louis XVI).",
            5: "La Commune censure les journaux royalistes. Clergé +2.",
            6: "Fête en l'honneur des morts du 10 août. Commune +1.",
            7: "Fête des sans-culottes. Commune -1.",
            8: "La Convention appelle les Parisiens au calme. Commune -1.",
            9: "Une délégation réclame du pain ; le Gouvernement décide. Oui : 300 assignats. Non : Commune +2, Renommée Gouvernement et Gironde -1.",
            10: "Pillage de la halle aux grains : le Gouvernement rend 200 assignats.",
            11: "Émeute du faubourg Saint-Antoine : Paris devient neutre.",
            12: "Une délégation réclame l'arrestation des Girondins. Commune +3.",
        },
    },
    'Terror': {
        'economy': {
            2: "Émeute agraire à Dijon : la région devient neutre, son ancien maître rend 100 assignats.",
            3: "Émeute agraire à Dijon : la région devient neutre, son ancien maître rend 100 assignats.",
            4: "Émeute agraire à Tours : la région devient neutre, son ancien maître rend 100 assignats.",
            5: "Émeute agraire à Tours : la région devient neutre, son ancien maître rend 100 assignats.",
            6: "Émeute agraire à Orléans : la région devient neutre, son ancien maître rend 200 assignats.",
            7: "Émeute agraire à Orléans : la région devient neutre, son ancien maître rend 200 assignats.",
            8: "Émeute agraire à Metz : la région devient neutre, son ancien maître rend 200 assignats.",
            9: "Émeute agraire à Metz : la région devient neutre, son ancien maître rend 200 assignats.",
            10: "Émeute agraire à Amiens : la région devient neutre, son ancien maître rend 300 assignats.",
            11: "Émeute agraire à Amiens : la région devient neutre, son ancien maître rend 300 assignats.",
            12: "Émeute agraire à Marseille : la région se révolte et devient neutre.",
        },
        'politics': {
            2: "Charlotte Corday assassine Marat.",
            3: "Révolte girondine à Caen menée par le général Wimpfen.",
            4: "Roux appelle à l'insurrection contre le Gouvernement montagnard : Renommée Montagne -1, sauf si Roux est arrêté avant la fin du tour.",
            5: "Hébert accuse Robespierre et Danton de modération : Renommée Montagne -2, sauf si les Exagérés sont mis hors-la-loi avant la fin du tour.",
            6: "Hébert accuse Robespierre et Danton de modération : Renommée Montagne -2, sauf si les Exagérés sont mis hors-la-loi avant la fin du tour.",
            7: "Discours de Danton pour l'indulgence contre Hébert : Renommée Montagne -2, sauf si les Exagérés sont mis hors-la-loi ce tour ; +2 pour les mettre hors-la-loi.",
            8: "Discours de Danton pour l'indulgence contre Hébert : Renommée Montagne -2, sauf si les Exagérés sont mis hors-la-loi ce tour ; +2 pour les mettre hors-la-loi.",
            9: "Politique de la Terreur : le Gouvernement a +2 pour calmer les révoltes, arrêter et mettre hors-la-loi Indulgents et Exagérés.",
            10: "Politique de la Terreur : le Gouvernement a +2 pour calmer les révoltes, arrêter et mettre hors-la-loi Indulgents et Exagérés.",
            11: "Saint-Just et Barère font l'éloge de Robespierre : Renommée Montagne +1 et +2 à tous les votes ce tour.",
            12: "Discours des thermidoriens contre Robespierre : -4 à tous les votes ce tour.",
        },
        'counter': {
            2: "Émeutes royalistes à Angers : la région devient neutre, sauf si le Royaliste la contrôle.",
            3: "Émeutes royalistes à Angers : la région devient neutre, sauf si le Royaliste la contrôle.",
            4: "Émeutes royalistes à Nantes : la région devient neutre, sauf si le Royaliste la contrôle.",
            5: "Émeutes royalistes à Nantes : la région devient neutre, sauf si le Royaliste la contrôle.",
            6: "Révolte royaliste à Marseille, contrôlée par le Royaliste.",
            7: "Révolte royaliste à Marseille, contrôlée par le Royaliste.",
            8: "Révolte royaliste à Cholet, contrôlée par le Royaliste.",
            9: "Révolte royaliste à Cholet, contrôlée par le Royaliste.",
            10: "Révolte royaliste à Lyon, contrôlée par le Royaliste.",
            11: "Révolte royaliste à Lyon, contrôlée par le Royaliste.",
            12: "Révolte royaliste à Lyon, contrôlée par le Royaliste.",
        },
        'commune': {
            2: "Fête de la Raison. Commune +2.",
            3: "Fête de la Raison. Commune +2.",
            4: "Fêtes révolutionnaires. Commune -2.",
            5: "Fêtes révolutionnaires. Commune -2.",
            6: "Création de l'armée révolutionnaire de Paris : le Gouvernement a une armée de plus ce tour.",
            7: "On réclame l'exécution de Marie-Antoinette et de Philippe Égalité ; le Gouvernement décide. Oui : Renommée Gouvernement +2, Commune -3. Non : Renommée Gouvernement -1, Commune +3.",
            8: "On réclame la mise en accusation des Indulgents : +2 pour les mettre hors-la-loi ce tour.",
            9: "On réclame la mise en accusation des Indulgents : +2 pour les mettre hors-la-loi ce tour.",
            10: "La Commune réclame du pain ; le Gouvernement décide. Oui : Renommée Gouvernement +1, 300 assignats. Non : Paris devient neutre, 200 assignats.",
            11: "La Commune réclame du pain ; le Gouvernement décide. Oui : Renommée Gouvernement +1, 300 assignats. Non : Paris devient neutre, 200 assignats.",
            12: "Agitation des sans-culottes parisiens : Paris devient neutre, le Gouvernement rend 200 assignats.",
        },
    },
    'Thermidor': {
        'economy': {
            2: "Émeute terroriste à Nîmes : la région devient neutre.",
            3: "Émeute terroriste à Strasbourg : la région devient neutre.",
            4: "Émeute terroriste à Lyon : la région devient neutre.",
            5: "Émeute terroriste à Marseille : la région devient neutre.",
            6: "Terreur blanche à Strasbourg : le Feuillant prend la région.",
            7: "Terreur blanche à Nîmes : le Feuillant prend la région.",
            8: "Terreur blanche à Marseille : le Feuillant prend la région.",
            9: "Terreur blanche à Lyon : le Feuillant prend la région.",
            10: "Émeute agraire à Orléans : la région devient neutre, le Gouvernement rend 200 assignats.",
            11: "Émeute agraire à Rouen : la région devient neutre, le Gouvernement rend 300 assignats.",
            12: "Hausse générale des prix. Commune +5, Économie +5.",
        },
        'politics': {
            2: "Mme de Staël intrigue dans son salon : le Feuillant a +2 pour retourner députés et personnalités.",
            3: "Mme de Staël intrigue dans son salon : le Feuillant a +2 pour retourner députés et personnalités.",
            4: "Mme Tallien intrigue dans son salon : la Montagne a +2 pour retourner députés et personnalités.",
            5: "Mme Tallien intrigue dans son salon : la Montagne a +2 pour retourner députés et personnalités.",
            6: "Babeuf appelle à l'insurrection pacifique. Commune +2.",
            7: "Discours thermidoriens contre les terroristes : +2 pour mettre les Terroristes hors-la-loi.",
            8: "Discours thermidoriens contre les terroristes : +2 pour mettre les Terroristes hors-la-loi.",
            9: "Agents thermidoriens : le Gouvernement a +2 pour calmer les révoltes et arrêter.",
            10: "Billaud-Varenne, Collot d'Herbois et Barère attaquent les thermidoriens : Renommée Marais -2, sauf si les Terroristes sont mis hors-la-loi ce tour. Barère passe à la Montagne.",
            11: "Les chefs feuillants agitent Paris : le Feuillant peut soulever la Commune ce tour, sans malus.",
            12: "Barras appelle Bonaparte pour rétablir l'ordre à Paris. Commune -5, la Commune se calme.",
        },
        'counter': {
            2: "Rupture entre Charette et Stofflet. Clergé -4.",
            3: "Rupture entre Charette et Stofflet. Clergé -4.",
            4: "Paix de Bâle avec la Prusse et l'Espagne : armées prussienne et espagnoles retirées. Coalisés -5, Clergé -2.",
            5: "Paix de Bâle avec la Prusse et l'Espagne : armées prussienne et espagnoles retirées. Coalisés -5, Clergé -2.",
            6: "Paix de La Jaunaye avec l'armée catholique et royale. Clergé -5.",
            7: "Paix de La Jaunaye avec l'armée catholique et royale. Clergé -5.",
            8: "Mort de Louis XVII. Clergé +2.",
            9: "Stofflet et Charette appellent à l'insurrection. Clergé +4.",
            10: "Stofflet et Charette appellent à l'insurrection. Clergé +4.",
            11: "Révolte royaliste à Brest.",
            12: "Révolte royaliste à Cholet.",
        },
        'commune': {
            2: "Dénonciations contre les anciens terroristes : +2 pour arrêter les Sans-Culottes et Montagnards hors-la-loi.",
            3: "Dénonciations contre les anciens terroristes : +2 pour arrêter les Sans-Culottes et Montagnards hors-la-loi.",
            4: "Les muscadins s'opposent à la fête de la mort de Louis XVI. Commune -2.",
            5: "Les muscadins s'opposent à la fête de la mort de Louis XVI. Commune -2.",
            6: "Les muscadins harcèlent anciens jacobins et terroristes. Commune -4.",
            7: "Les muscadins harcèlent anciens jacobins et terroristes. Commune -4.",
            8: "On demande la paix au Gouvernement, qui décide. Oui : Renommée Gouvernement +1, 300 assignats. Non : Renommée Gouvernement -1, Commune +3.",
            9: "On demande la paix au Gouvernement, qui décide. Oui : Renommée Gouvernement +1, 300 assignats. Non : Renommée Gouvernement -1, Commune +3.",
            10: "On demande la paix au Gouvernement, qui décide. Oui : Renommée Gouvernement +1, 300 assignats. Non : Renommée Gouvernement -1, Commune +3.",
            11: "Révolte agraire à Paris : la Commune se soulève, sans meneur.",
            12: "Révolte agraire à Paris : la Commune se soulève, sans meneur.",
        },
    },
}
